set_property SRC_FILE_INFO {cfile:D:/wza/vivado_program_files/project_for_digital_logic/I2C_driver/vivado-proj/vivado-proj.srcs/constrs_1/new/servo_driver_top.xdc rfile:../../../vivado-proj.srcs/constrs_1/new/servo_driver_top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports i_clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports i_rst_n]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports io_SDA]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports o_SCL]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_rst_n_IBUF]
