# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath F:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/wza/vivado_program_files/project_for_digital_logic/program_control_1/vivado-proj/vivado-proj.cache/wt [current_project]
set_property parent.project_path D:/wza/vivado_program_files/project_for_digital_logic/program_control_1/vivado-proj/vivado-proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/wza/vivado_program_files/project_for_digital_logic/program_control_1/src/time_divider.v
  D:/wza/vivado_program_files/project_for_digital_logic/program_control_1/src/counter_overflow.v
  D:/wza/vivado_program_files/project_for_digital_logic/program_control_1/src/program_control_1.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/wza/vivado_program_files/project_for_digital_logic/program_control_1/vivado-proj/vivado-proj.srcs/constrs_1/new/program_control_1.xdc
set_property used_in_implementation false [get_files D:/wza/vivado_program_files/project_for_digital_logic/program_control_1/vivado-proj/vivado-proj.srcs/constrs_1/new/program_control_1.xdc]


synth_design -top program_control_1 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef program_control_1.dcp

catch { report_utilization -file program_control_1_utilization_synth.rpt -pb program_control_1_utilization_synth.pb }
