# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath F:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/wza/vivado_program_files/project_for_digital_logic/I2C_driver/vivado-proj/vivado-proj.cache/wt [current_project]
set_property parent.project_path D:/wza/vivado_program_files/project_for_digital_logic/I2C_driver/vivado-proj/vivado-proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/wza/vivado_program_files/project_for_digital_logic/I2C_driver/src/time_divider.v
  D:/wza/vivado_program_files/project_for_digital_logic/I2C_driver/src/I2C_frame_output.v
  D:/wza/vivado_program_files/project_for_digital_logic/I2C_driver/src/servo_driver.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top servo_driver -part xc7a100tcsg324-1


write_checkpoint -force -noxdef servo_driver.dcp

catch { report_utilization -file servo_driver_utilization_synth.rpt -pb servo_driver_utilization_synth.pb }
