set_property IOSTANDARD LVCMOS33 [get_ports i_rst_n]
set_property PACKAGE_PIN V10 [get_ports i_rst_n]






# set_property IOSTANDARD LVCMOS33 [get_ports i_sclk]
# set_property IOSTANDARD LVCMOS33 [get_ports i_data]
# set_property PACKAGE_PIN F4 [get_ports i_sclk]
# set_property PACKAGE_PIN B2 [get_ports i_data]



set_property IOSTANDARD LVCMOS33 [get_ports {o_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[0]}]
set_property PACKAGE_PIN H17 [get_ports {o_data[0]}]
set_property PACKAGE_PIN K15 [get_ports {o_data[1]}]
set_property PACKAGE_PIN J13 [get_ports {o_data[2]}]
set_property PACKAGE_PIN N14 [get_ports {o_data[3]}]
set_property PACKAGE_PIN R18 [get_ports {o_data[4]}]
set_property PACKAGE_PIN V17 [get_ports {o_data[5]}]
set_property PACKAGE_PIN U17 [get_ports {o_data[6]}]
set_property PACKAGE_PIN U16 [get_ports {o_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports i_ps2_sclk]
set_property PACKAGE_PIN E3 [get_ports i_clk]
set_property PACKAGE_PIN B2 [get_ports i_ps2_data]
set_property PACKAGE_PIN F4 [get_ports i_ps2_sclk]


set_property IOSTANDARD LVCMOS33 [get_ports {o_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_data[8]}]
set_property PACKAGE_PIN V16 [get_ports {o_data[8]}]
set_property PACKAGE_PIN T15 [get_ports {o_data[9]}]
set_property PACKAGE_PIN U14 [get_ports {o_data[10]}]
set_property PACKAGE_PIN T16 [get_ports {o_data[11]}]
set_property PACKAGE_PIN V15 [get_ports {o_data[12]}]


set_property IOSTANDARD LVCMOS33 [get_ports o_servo0]
set_property PACKAGE_PIN C17 [get_ports o_servo0]
#
set_property PACKAGE_PIN A4 [get_ports {vga_rgb[11]}]
set_property PACKAGE_PIN C5 [get_ports {vga_rgb[10]}]
set_property PACKAGE_PIN B4 [get_ports {vga_rgb[9]}]
set_property PACKAGE_PIN A3 [get_ports {vga_rgb[8]}]
set_property PACKAGE_PIN A6 [get_ports {vga_rgb[7]}]
set_property PACKAGE_PIN B6 [get_ports {vga_rgb[6]}]
set_property PACKAGE_PIN A5 [get_ports {vga_rgb[5]}]
set_property PACKAGE_PIN C6 [get_ports {vga_rgb[4]}]
set_property PACKAGE_PIN D8 [get_ports {vga_rgb[3]}]
set_property PACKAGE_PIN D7 [get_ports {vga_rgb[2]}]
set_property PACKAGE_PIN C7 [get_ports {vga_rgb[1]}]
set_property PACKAGE_PIN B7 [get_ports {vga_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[0]}]
set_property PACKAGE_PIN B11 [get_ports vga_hs]
set_property PACKAGE_PIN B12 [get_ports vga_vs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_adv_clk]
set_property IOSTANDARD LVCMOS33 [get_ports vga_blank_n]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_sync_n]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]


set_property PACKAGE_PIN V11 [get_ports vga_blank_n]
set_property PACKAGE_PIN V12 [get_ports vga_adv_clk]
set_property PACKAGE_PIN V14 [get_ports vga_sync_n]
