######################################################################
#
# File name : program_control_1_tb_compile.do
# Created on: Fri Dec 31 12:29:33 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modeltech_pe_10.4c\\win32pe\\vlib work
F:\\modeltech_pe_10.4c\\win32pe\\vlib msim

F:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

F:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

F:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../../src/counter_overflow.v" \
"../../../../src/time_divider.v" \
"../../../../src/program_control_1.v" \
"../../../../src/program_control_1_tb.v" \


# compile glbl module
F:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

