######################################################################
#
# File name : program_control_1_tb_wave.do
# Created on: Fri Dec 31 12:29:51 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
