######################################################################
#
# File name : program_control_1_tb_simulate.do
# Created on: Fri Dec 31 12:29:51 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.program_control_1_tb xil_defaultlib.glbl

do {program_control_1_tb_wave.do}

view wave
view structure
view signals

do {program_control_1_tb.udo}

run 1000ns
